### PR TITLE
Make newEstimate in addWorklog optional

### PR DESCRIPTION
**Pull request by santi-git**
In JIRA API worklogs are optional, but the wrapper forces the user to set one. Removing it solved the issue for me.

### CODE REVIEW

**Comment by pioug** [comment]
Cross-reference https://github.com/jira-node/node-jira-client/pull/212

**Comment by dkokic** [comment]
I see this PR is superseded by #212

**Comment by santi-git** [comment]
Sorry, I've been away for some time should I close this one. I've seen it's been fixed on another PR

**Comment by pioug** [comment]
@santi-git Thanks for following up 👍 I am closing the PR then. Feel free to open a new PR/issue if the current implementation doesn't work for you.

**Pull request closed without merging**
