### PR TITLE
Add Get Sprint Function

### PR DESCRIPTION
**Pull request by MrLoh**
I needed a function to get sprint details like start and end dates. Also added a `genericAgileGet` function since that would have also solved my usecase but was missing as well

### CODE REVIEW

**Comment by MrLoh** [comment]
@pioug wow that was fast ❤️ What version will this be in, I'm also filing a PR to definitely types

**Comment by MrLoh** [comment]
I guess that would be 7.1 which you just released awesome

**Comment by MrLoh** [comment]
here's the corresponding definitely typed update just for my own reference
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57011

**Comment by pioug** [comment]
@MrLoh Thanks for your contribution! Correct, it's in v7.1.0. I added you to the repo as a collaborator. Feel free to get more involve in the project!

**Comment by MrLoh** [comment]
will do if I encounter any more things I need, so far it's been a really useful little library

**Pull request merged**
